version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
     - POSTGRES_USER=test
     - POSTGRES_PASSWORD=123
     - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
